### PR TITLE
Repair for Multiprocessing

### PR DESCRIPTION
**Pull request by jpn--**
This is a multi-faceted solution to your current problems .

First, there are changes to the ActivitySim code base.  There are a lot of changes in https://github.com/ActivitySim/activitysim/pull/654 , but the important one for PSRC's MAZ issue is here:

https://github.com/camsys/activitysim/blob/cc3560e2800cc6e67ce96302a0f12f8c03b83e06/activitysim/core/los.py#L298-L313

This should promote the indexing dtype for the MAZ LOS tables based on the MAZ ceiling, so that it will not overflow.

Second, in your implementation, you need to slice _only_ the accessibilities table for the accessibilities MP step.  Historically, this step has been coded to slice everything, and before the sharrow zone recoding was added, that was harmless.  With the recoding, you need to pass the full MAZ and TAZ tables to each MP worker, so they can map the zone numbers correctly.

I have done that as an example in the test directory for your repo:

https://github.com/jpn--/psrc_activitysim/blob/4a6732cc9485fb1df80c3b04a4a72a01c804f7bc/test/configs_mp/settings_mp.yaml#L26

Applying the same fix in all the other MP settings files is left as an exercise for the reader.

If it is important to you, I can try to dissect the fix out of my ORCA branch and make a minimal PR that should fix the problem.  But I think it might be easier to just move forward with the fix and all the new testing infrastructure I built to support it.

### CODE REVIEW

**Comment by stefancoe** [comment]
Thanks @jpn-- much appreciated! I might have more questions, but here is my first. It looks like you had to make changes to the skims, possibly with this script:
https://github.com/psrc/psrc_activitysim/blob/a59f2187db55a443f726dcfaa5719a28b8e334db/extensions/skims_preprocess.py

Can you let me know what this doing. Is it related to the VOT categories we have added? Just an FYI, the configs we are using to support VOT segmentation and all other development (including changes to support sharrow) are located in [settings_dev](https://github.com/psrc/psrc_activitysim/tree/main/configs_dev). Thanks again.

**Comment by stefancoe** [comment]
@jpn-- Thinking about this a little more, I imagine the changes you made are to make the skims compatible with the configs that are currently being used for the psrc example?

**Comment by jpn--** [comment]
Yeah, sorry I forget I changed the skims.  The configs_dev calls for VOT segmentations, but the OMX test file within the repo didn't have any of the VOT segmentations in it.  So I created them by simply duplicating each relevant skim table into *_L, *_M, an *_H names.  If you have skims that have those tables with differentiated values, you can just swap out for that and have a better result.

**Comment by stefancoe** [comment]
Ok, got it. Thanks. I will clone this https://github.com/camsys/activitysim/tree/generic-whale and test it. No need to make a separate pull request for this issue.

**Comment by stefancoe** [comment]
@jpn-- I am getting this error 
'pypyr.errors.KeyNotInContextError: context['skim_dataset'] doesn't exist. It must exist for State.

I have attached the log. This happens using the data in [test on main](https://github.com/psrc/psrc_activitysim/tree/main/test) and using our latest data, which is on the [mp_repair branch](https://github.com/psrc/psrc_activitysim/tree/mp_repair/test). 

Let me know if I can provide any more details. Also, I thought I had pushed our latest skims with VOT segmentation, but clearly had not, hence my confusion yesterday.  Thanks!
[activitysim.log](https://github.com/psrc/psrc_activitysim/files/11053571/activitysim.log)

**Comment by stefancoe** [comment]
Thanks- that worked! Question- is using sharrow and chunking together incompatible?

**Comment by stefancoe** [comment]
@jpn-- There is a potential bug/better error handling opportunity [here](https://github.com/camsys/activitysim/blob/d783097a09ec66dcbe0d4bc5418cb25d9ddc1f1d/activitysim/core/interaction_sample_simulate.py#L310). When running trip destination, and as a result of some recent specification changes, we have some trips that [have really low logsum utilities](https://github.com/psrc/psrc_activitysim/blob/main/configs_dev/trip_destination.csv#L17) for every alternative in the choice set. In fact, they are lower than -999, [which is what the padded utilities are set to](https://github.com/camsys/activitysim/blob/d783097a09ec66dcbe0d4bc5418cb25d9ddc1f1d/activitysim/core/interaction_sample_simulate.py#L225). This results in 0 probabilities across all alternatives during [this step](https://github.com/camsys/activitysim/blob/d783097a09ec66dcbe0d4bc5418cb25d9ddc1f1d/activitysim/core/interaction_sample_simulate.py#L251), except for the padded alternatives  and therefore one of the padded alternatives is chosen. Because the returned [position](https://github.com/camsys/activitysim/blob/d783097a09ec66dcbe0d4bc5418cb25d9ddc1f1d/activitysim/core/interaction_sample_simulate.py#L307) of the padded alternative is higher than the trip's positions in the alternatives table, no alternatives are selected for the trip, but instead the next trip gets two alternatives assigned to it, unless it also has all 0 probabilities. This results in the error: 'cannot reindex on an axis with duplicate labels' on line 310. 

This [assert](https://github.com/camsys/activitysim/blob/d783097a09ec66dcbe0d4bc5418cb25d9ddc1f1d/activitysim/core/interaction_sample_simulate.py#L300) statement is designed to catch this issue, but positions.max() is 0 based and I think it will always be 1 less than max_sample_count. Obviously the root cause of this is our specification and/or data and needs to be fixed, but I figured it might be worth handling these as failed trips or some other way. Also, i decided to post this here instead of as new issue because I dont think this fix is in the main repo yet. Happy to post it as an issue once that happens if it has not been resolved. I will also post a separate issue on this repo about out logsum issue. Thanks! 

[probs-095bb7.csv](https://github.com/psrc/psrc_activitysim/files/11094644/probs-095bb7.csv)

**Comment by jpn--** [comment]
Thanks for this tip @stefancoe.

In the meantime, do you have an up-to-date set of "medium" scale model input files you could share?  There's a "[Seattle](https://github.com/ActivitySim/activitysim_resources/tree/master/psrc_data_seattle)" model but it appears out-of-date, and I'd like to do some testing on something bigger than the mini-test sized model but not quite so laptop-stretching as the full scale PSRC region, without spending a lot of time creating that data myself if you already have it handy.

**Comment by stefancoe** [comment]
@jpn-- Sure thing. Would the full dataset work? It's about 13 GBs and includes an accessibility file so that step can be skipped. I think this error happens on long tours so I want to make sure you can replicate it. Otherwise I can try to get something setup tomorrow that will produce the error. 

One last question- In the file below, are the MAZs in alt_dest the 0 based index of the MAZ file? For example, if my MAZ system went 1,2,3,5..., MAZ 5 would be 3 in the trace files? Thanks!
 
[alternatives-5689a0.csv](https://github.com/psrc/psrc_activitysim/files/11095922/alternatives-5689a0.csv)

**Comment by jpn--** [comment]
I can try working with the whole full dataset, go ahead and share a link.

Not urgently but eventually, if we can reproduce the error in a medium-size dataset, that will help with being able to set up testing to ensure it stays fixed.  The full size data is unwieldy but workable for development, but it's just too large to run regularly inside a GitHub actions worker.

As for the trace files, yes the zero-recoded zone numbers are output in the trace files.  There are no instructions carried around inside components about what variables are what kind of zone number to do the decoding of those readily within the tracing outputs.

**Comment by stefancoe** [comment]
Ok, cool. Here it is:
https://drive.google.com/drive/folders/1r91K54QdAVGDYzSkkqgncXFLlpqGRvtc?usp=sharing

I'll start working on a medium-sized dataset that reproduces the error and thanks for the clarification about the tracing outputs.

**Comment by stefancoe** [comment]
Oh one more thing- I have been running it with 100k households.

**Comment by stefancoe** [comment]
@jpn-- Please use the tour mode choice coefficient file I just pushed to main. The existing one causes an error in school location because of a wrong signed coefficient.
 
https://github.com/psrc/psrc_activitysim/tree/main/configs_dev

**Pull request merged**
