### PR TITLE
Testing and fixing

### PR DESCRIPTION
**Pull request by jpn--**
This PR includes infrastructure to run tests on the (test-size) PSRC model using the [explicit-chunk](https://github.com/camsys/activitysim/tree/explicit-chunk) branch of the ActivitySim codebase.  Note the test-size data doesn't actually exercise the explicit chunking, but it worked for me on your full-size data.  The full size test with 100K households runs *almost* all the way (see notebook linked below), there's a single trip that has a mode choice failure on the last step.  Also there's a link below to a revised accessibility table; the table you shared earlier via google lacked the "TotalAcc" column, but since explicit chunking lets me run accessibility easily (if slowly) on my laptop I just regenerated it.

- [jupyter notebook with run on full data](https://camsys-my.sharepoint.com/:u:/p/jeffnewman/EbTQDOsGZd5Jrm3Ykwf211ABCHJFIkfjBAzOUySCshMvXQ?e=2Xoyna)
- [precomputed_accessibility.parquet](https://camsys-my.sharepoint.com/:u:/p/jeffnewman/EXCam9yOt45MjaNB71Bxx3gBwS_jNLW-XlSgj-fQ389Obw?e=QAJCgl)

I've not made any attempt to validate the test results as "correct", I just confirmed that they run without error and are reproducible in GitHub actions.  The regression test outputs do change from before at least because you've changed the underlying model parameters.

You may want to disable the ".github/workflows/ci.yaml" workflow for push and PR triggers, as any change you make to parameters, model components, sequences, etc. will break these tests.  But I think having that workflow available, at least on the "workflow_dispatch" trigger (i.e., manual run), will be useful for you and as an example/template for other agencies to follow.

### CODE REVIEW

**Comment by stefancoe** [comment]
@jpn-- Thanks, I will take a look. I am curious though, how did you get it to run using the full data and 100k households without running into the self.maz_ceiling.astype issue:

https://github.com/ActivitySim/activitysim/issues/640

-Stefan

**Comment by jpn--** [comment]
p.s. the GitHub actions won't run in your repo unless you enable them (it's a GutHub security feature).  But you should be able to see the actions do run in my fork [here](https://github.com/jpn--/psrc_activitysim/actions)

**Comment by stefancoe** [comment]
@jpn-- I tested the explicit chunking version and it works great. Are you planning to add the same functionality to all models? Or just the ones that are known to use a lot of RAM? Also, I appreciate you adding the testing infrastructure and thought maybe you could discuss this briefly at one of our meetings. Since we are making lots of changes to our specifications, it seems like most commits would cause the tests to fail. Just curious what role you see this having in such a workflow. Thanks again for all of your help/support!

**Comment by jpn--** [comment]
> Are you planning to add the same functionality to all models?

There are no specific plans for what to do next with the explicit chunking.  Implementing it at all was something I did on my own just for one model to see of it could work easily and how hard it would be.  It's not an enumerated/funded task in this phase; rolling it out to other model components is something the consortium could choose to divert resources towards from the "general support" task, although there's already been quite a bit of diversion from that pool of funds already.

> Since we are making lots of changes to our specifications, it seems like most commits would cause the tests to fail.

Yes, the testing infrastructure on individual implementations is not something you want to pay attention to during active model development; every change you make to anything anywhere is almost certain to change the ultimate results (if it doesn't, why are you changing it?) and make the tests fail.  The testing infrastructure is appropriate for a stable branch or final model design destined for a stable branch, when you are ready to put a seal of approval on the whole model and will want to know that the results are stable against future possible changes in the ActivitySim codebase.

**Comment by stefancoe** [comment]
@jpn-- Thanks! Both points make sense.

**Pull request merged**
